CREATE TABLE IF NOT EXISTS locations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pos_x INT NOT NULL,
    pos_y INT NOT NULL,
    tile_type ENUM('wasteland','city','dungeon','radzone','vault','mountain') DEFAULT 'wasteland',
    tile_name VARCHAR(100) NULL,
    description TEXT NULL,
    danger_level TINYINT UNSIGNED DEFAULT 1,
    radiation_level TINYINT UNSIGNED DEFAULT 0,
    loot_quality TINYINT UNSIGNED DEFAULT 1,
    is_vault TINYINT(1) DEFAULT 0,
    is_dungeon TINYINT(1) DEFAULT 0,
    dungeon_size TINYINT UNSIGNED DEFAULT 0,
    is_border TINYINT(1) DEFAULT 0,
    border_direction ENUM('north','south','east','west') NULL,
    border_message VARCHAR(255) NULL,
    weather_resistant TINYINT(1) DEFAULT 0,
    scene_key VARCHAR(50) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_coords (pos_x, pos_y),
    INDEX idx_type (tile_type, is_dungeon, is_vault),
    INDEX idx_danger (danger_level, radiation_level),
    INDEX idx_vault (is_vault),
    INDEX idx_dungeon (is_dungeon, dungeon_size)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;