CREATE TABLE IF NOT EXISTS weapons (
    id INT AUTO_INCREMENT PRIMARY KEY,
    item_key VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    weight DECIMAL(5,2) DEFAULT 0,
    value INT UNSIGNED DEFAULT 0,
    dmg_dice TINYINT UNSIGNED DEFAULT 4,
    dmg_mod TINYINT SIGNED DEFAULT 0,
    crit_chance DECIMAL(4,1) DEFAULT 5.0,
    crit_mult DECIMAL(3,2) DEFAULT 1.5,
    range_type ENUM('melee', 'short', 'medium', 'long') DEFAULT 'melee',
    min_range TINYINT UNSIGNED DEFAULT 0,
    max_range TINYINT UNSIGNED DEFAULT 1,
    min_str TINYINT UNSIGNED DEFAULT 0,
    min_per TINYINT UNSIGNED DEFAULT 0,
    min_end TINYINT UNSIGNED DEFAULT 0,
    min_cha TINYINT UNSIGNED DEFAULT 0,
    min_int TINYINT UNSIGNED DEFAULT 0,
    min_agi TINYINT UNSIGNED DEFAULT 0,
    min_luk TINYINT UNSIGNED DEFAULT 0,
    is_active TINYINT(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_key (item_key),
    INDEX idx_range (range_type, min_range, max_range),
    INDEX idx_damage (dmg_dice, dmg_mod)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS armors (
    id INT AUTO_INCREMENT PRIMARY KEY,
    item_key VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    weight DECIMAL(5,2) DEFAULT 0,
    value INT UNSIGNED DEFAULT 0,
    defense TINYINT UNSIGNED DEFAULT 0,
    rad_resistance TINYINT UNSIGNED DEFAULT 0,
    slot_type ENUM('head', 'tors', 'arms', 'legs', 'full_body') DEFAULT 'tors',
    min_str TINYINT UNSIGNED DEFAULT 0,
    min_per TINYINT UNSIGNED DEFAULT 0,
    min_end TINYINT UNSIGNED DEFAULT 0,
    min_cha TINYINT UNSIGNED DEFAULT 0,
    min_int TINYINT UNSIGNED DEFAULT 0,
    min_agi TINYINT UNSIGNED DEFAULT 0,
    min_luk TINYINT UNSIGNED DEFAULT 0,
    is_active TINYINT(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_key (item_key),
    INDEX idx_slot (slot_type),
    INDEX idx_defense (defense, rad_resistance)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS consumables (
    id INT AUTO_INCREMENT PRIMARY KEY,
    item_key VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    weight DECIMAL(5,2) DEFAULT 0,
    value INT UNSIGNED DEFAULT 0,
    heal_amount SMALLINT SIGNED DEFAULT 0,
    rad_heal SMALLINT SIGNED DEFAULT 0,
    addiction_chance DECIMAL(4,1) DEFAULT 0.0,
    boost_type VARCHAR(50) DEFAULT NULL,
    boost_value TINYINT SIGNED DEFAULT 0,
    boost_duration TINYINT UNSIGNED DEFAULT 0,
    effect_duration TINYINT UNSIGNED DEFAULT 0,
    special_effect VARCHAR(100) DEFAULT NULL,
    is_active TINYINT(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_key (item_key),
    INDEX idx_boost (boost_type, boost_duration),
    INDEX idx_heal (heal_amount, rad_heal)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS loot (
    id INT AUTO_INCREMENT PRIMARY KEY,
    item_key VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    weight DECIMAL(5,2) DEFAULT 0,
    value INT UNSIGNED DEFAULT 0,
    category ENUM('junk', 'key_item', 'quest', 'component', 'currency') DEFAULT 'junk',
    stackable TINYINT(1) DEFAULT 1,
    max_stack INT UNSIGNED DEFAULT 99,
    is_active TINYINT(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_key (item_key),
    INDEX idx_category (category, stackable)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;